## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [73]:
import numpy as np
n = 10
a = np.sort(np.arange(n))[::-1]

b = np.arange(n-1, -1, -1)
print(a, b)


[9 8 7 6 5 4 3 2 1 0] [9 8 7 6 5 4 3 2 1 0]


## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [91]:
n = 10
mat = np.diag(np.arange(n-1, -1, -1))
s = 0

for i in range(len(mat)):
    for j in range(len(mat[i])):
        if i == j:
            s = s + mat[i][j]
print(mat)
print('Вариант А', np.sum(mat), '\nВариант Б', np.sum(mat))

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Вариант А 45 
Вариант Б 45


## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [220]:
s = np.array([[4, 2, 1, 4], [1, 3, 0, 12], [0, 5, 4, -3]])

d = np.linalg.det(s[:, 0:3])

if d != 0:
    x = np.linalg.det(np.column_stack((s[:, -1:], s[:, 1:3]))) / d
    y = np.linalg.det(np.column_stack((s[:,0:1],s[:, -1:], s[:, 2:3]))) / d
    z = np.linalg.det(np.column_stack((s[:,0:2],s[:, -1:]))) / d
print(x, y, z)

[[ 4  2  1  4]
 [ 1  3  0 12]
 [ 0  5  4 -3]]
0.46666666666666695 3.8444444444444463 -5.555555555555554


## Задание 4

In [282]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

c = np.array([])

def cs_cos(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

for i in users_stats:
    c = np.append(c, cs_cos(i, next_user_stats))

np.argmax(c)

7